services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.19
    networks:
      - configarr-full
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SONARR__APP__INSTANCENAME=Sonarr
      - SONARR__AUTH__APIKEY=5e792b7e0fe14f58b8e92bf0902d4a44
      - SONARR__AUTH__REQUIRED=DisabledForLocalAddresses
      - SONARR__AUTH__METHOD=Forms
    volumes:
      - sonarr:/config
    ports:
      - 6500:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:6.3.0
    networks:
      - configarr-full
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - RADARR__APP__INSTANCENAME=Radarr
      - RADARR__AUTH__APIKEY=0daa3a2b940f4e08bac991e9a30e9e12
      - RADARR__AUTH__REQUIRED=DisabledForLocalAddresses
      - RADARR__AUTH__METHOD=Forms
    volumes:
      - radarr:/config
      - radarr-download1:/downloads/1
      - radarr-download2:/downloads/2
    ports:
      - 6501:7878
    restart: unless-stopped

  # experimental
  whisparr:
    image: ghcr.io/hotio/whisparr:v3-3.0.0.695
    networks:
      - configarr-full
    ports:
      - "6502:6969"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
      - WHISPARR__APP__INSTANCENAME=Whisparr
      - WHISPARR__AUTH__APIKEY=2ebd18db81e14c2d98d06ef4b865aaa8
      - WHISPARR__AUTH__REQUIRED=DisabledForLocalAddresses
      - WHISPARR__AUTH__METHOD=Forms
    volumes:
      - whisparr:/config
    restart: unless-stopped

  # experimental
  readarr:
    image: lscr.io/linuxserver/readarr:develop-0.4.3.2665-ls130
    networks:
      - configarr-full
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - READARR__APP__INSTANCENAME=Readarr
      - READARR__AUTH__APIKEY=e001718ba38a424d8aae7cb391b5d27a
      - READARR__AUTH__REQUIRED=DisabledForLocalAddresses
      - READARR__AUTH__METHOD=Forms
    volumes:
      - readarr:/config
    ports:
      - 6503:8787
    restart: unless-stopped

  # experimental
  lidarr:
    image: lscr.io/linuxserver/lidarr:2.14.5
    networks:
      - configarr-full
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - LIDARR__APP__INSTANCENAME=Lidarr
      - LIDARR__AUTH__APIKEY=713067b7319045df9c7fa6847d8ce717
      - LIDARR__AUTH__REQUIRED=DisabledForLocalAddresses
      - LIDARR__AUTH__METHOD=Forms
    volumes:
      - lidarr:/config
    ports:
      - 6504:8686
    restart: unless-stopped

networks:
  configarr-full:
    name: configarr-full

volumes:
  sonarr:
  radarr:
  whisparr:
  readarr:
  lidarr:
  radarr-download1:
  radarr-download2:
