services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.11
    networks:
      - configarr-full
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - sonarr:/config
      - ${PWD}/sonarr.xml:/config/config.xml:rw
    ports:
      - 6500:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:5.16.3
    networks:
      - configarr-full
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - radarr:/config
      - ${PWD}/radarr.xml:/config/config.xml:rw
    ports:
      - 6501:7878
    restart: unless-stopped

  # experimental
  whisparr:
    image: ghcr.io/hotio/whisparr:v3-3.0.0.695
    networks:
      - configarr-full
    ports:
      - "6502:6969"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - whisparr:/config
      - ${PWD}/whisparr.xml:/config/config.xml:rw
    restart: unless-stopped

  # experimental
  readarr:
    image: lscr.io/linuxserver/readarr:develop-0.4.3.2665-ls130
    networks:
      - configarr-full
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - readarr:/config
      - ${PWD}/readarr.xml:/config/config.xml:rw
    ports:
      - 6503:8787
    restart: unless-stopped

networks:
  configarr-full:
    name: configarr-full

volumes:
  sonarr:
  radarr:
  whisparr:
  readarr:
