name: Documentation (Preview)

on:
  pull_request:
    branches: [main]
    paths:
      - docs/**
  workflow_dispatch:

permissions: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    permissions:
      contents: read
      deployments: write
      pull-requests: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Inject enhanced GitHub environment variables
        uses: rlespinasse/github-slug-action@ef93b2ea4b6405d06fd8684fc3ff795d262ecae8 # v5.7.0

      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          version: latest

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: lts/*
          package-manager-cache: false

      - name: Install & build
        working-directory: docs
        env:
          PNPM_CONFIG_IGNORE_WORKSPACE: "true"
        run: |
          pnpm install --frozen-lockfile
          pnpm build

      - name: Set deploy branch
        id: deploy_branch
        env:
          DEPLOY_BRANCH: ${{ env.GITHUB_REF_SLUG_URL }}
        run: echo "value=${DEPLOY_BRANCH}" >> "$GITHUB_OUTPUT"

      - name: Deploy
        uses: cloudflare/wrangler-action@ebbaa1584979971c8614a24965b4405ff95890e0 # v4.0.0
        id: cloudflare-deploy
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          packageManager: npm
          command: pages deploy ./docs/build --project-name=configarr-preview --branch=${{ steps.deploy_branch.outputs.value }}

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3.0.1
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main' }}
        with:
          message: |
            Doc preview deployed to: ${{ steps.cloudflare-deploy.outputs.deployment-url }}
          comment-tag: docs-preview
